import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigate } from "./components/Navigate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigate />

        {children}
        <footer className="flex justify-between items-center px-6 py-3 bg-gray-800 text-white text-sm w-full fixed bottom-0">
          <span>© 2025 Pankaj Bamniya | YourBlog</span>
          <span>Privacy Policy | Terms & Conditions</span>
        </footer>
      </body>
    </html>
  );
}
